# Generated by Django 3.1.1 on 2020-09-13 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuju', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='song_name',
        ),
        migrations.AddField(
            model_name='song',
            name='song_tstamp',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='song',
            name='user_id',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_id',
            field=models.IntegerField(default=0),
        ),
    ]
